/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Something_H
#define Something_H

#include <thrift/TDispatchProcessor.h>
#include "test_types.h"

namespace Test {

class SomethingIf {
 public:
  virtual ~SomethingIf() {}
  virtual void ping(std::string& _return, const std::string& url) = 0;
};

class SomethingIfFactory {
 public:
  typedef SomethingIf Handler;

  virtual ~SomethingIfFactory() {}

  virtual SomethingIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SomethingIf* /* handler */) = 0;
};

class SomethingIfSingletonFactory : virtual public SomethingIfFactory {
 public:
  SomethingIfSingletonFactory(const boost::shared_ptr<SomethingIf>& iface) : iface_(iface) {}
  virtual ~SomethingIfSingletonFactory() {}

  virtual SomethingIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SomethingIf* /* handler */) {}

 protected:
  boost::shared_ptr<SomethingIf> iface_;
};

class SomethingNull : virtual public SomethingIf {
 public:
  virtual ~SomethingNull() {}
  void ping(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _Something_ping_args__isset {
  _Something_ping_args__isset() : url(false) {}
  bool url :1;
} _Something_ping_args__isset;

class Something_ping_args {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  Something_ping_args(const Something_ping_args&);
  Something_ping_args& operator=(const Something_ping_args&);
  Something_ping_args() : url() {
  }

  virtual ~Something_ping_args() throw();
  std::string url;

  _Something_ping_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const Something_ping_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const Something_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Something_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Something_ping_args& obj);
};


class Something_ping_pargs {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};


  virtual ~Something_ping_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Something_ping_pargs& obj);
};

typedef struct _Something_ping_result__isset {
  _Something_ping_result__isset() : success(false) {}
  bool success :1;
} _Something_ping_result__isset;

class Something_ping_result {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};

  Something_ping_result(const Something_ping_result&);
  Something_ping_result& operator=(const Something_ping_result&);
  Something_ping_result() : success() {
  }

  virtual ~Something_ping_result() throw();
  std::string success;

  _Something_ping_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Something_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Something_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Something_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Something_ping_result& obj);
};

typedef struct _Something_ping_presult__isset {
  _Something_ping_presult__isset() : success(false) {}
  bool success :1;
} _Something_ping_presult__isset;

class Something_ping_presult {
 public:

  static const char* ascii_fingerprint; // = "9A73381FEFD6B67F432E717102246330";
  static const uint8_t binary_fingerprint[16]; // = {0x9A,0x73,0x38,0x1F,0xEF,0xD6,0xB6,0x7F,0x43,0x2E,0x71,0x71,0x02,0x24,0x63,0x30};


  virtual ~Something_ping_presult() throw();
  std::string* success;

  _Something_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Something_ping_presult& obj);
};

class SomethingClient : virtual public SomethingIf {
 public:
  SomethingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SomethingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& url);
  void send_ping(const std::string& url);
  void recv_ping(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SomethingProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<SomethingIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (SomethingProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SomethingProcessor(boost::shared_ptr<SomethingIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &SomethingProcessor::process_ping;
  }

  virtual ~SomethingProcessor() {}
};

class SomethingProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SomethingProcessorFactory(const ::boost::shared_ptr< SomethingIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< SomethingIfFactory > handlerFactory_;
};

class SomethingMultiface : virtual public SomethingIf {
 public:
  SomethingMultiface(std::vector<boost::shared_ptr<SomethingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SomethingMultiface() {}
 protected:
  std::vector<boost::shared_ptr<SomethingIf> > ifaces_;
  SomethingMultiface() {}
  void add(boost::shared_ptr<SomethingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return, url);
    }
    ifaces_[i]->ping(_return, url);
    return;
  }

};

} // namespace

#endif
